[build-system]
requires = ["setuptools>=77.0.0", "setuptools_scm[toml]>=6.4.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dissect"
description = "Dissect is a digital forensics & incident response framework and toolset that allows you to quickly access and analyse forensic artefacts from various disk and file formats, developed by Fox-IT (part of NCC Group)"
readme = "README.md"
requires-python = ">=3.10"
license = "AGPL-3.0-or-later"
license-files = ["LICENSE", "COPYRIGHT"]
authors = [
  {name = "Dissect Team", email = "dissect@fox-it.com"}
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Topic :: Internet :: Log Analysis",
  "Topic :: Scientific/Engineering :: Information Analysis",
  "Topic :: Security",
  "Topic :: Utilities",
]
dependencies = [
    "dissect.apfs==1.1",
    "dissect.archive==1.8",
    "dissect.btrfs==1.10",
    "dissect.cim==3.13",
    "dissect.clfs==1.11",
    "dissect.cramfs==1.1",
    "dissect.cstruct==4.7",
    "dissect.database==1.1",
    "dissect.etl==3.14",
    "dissect.eventlog==3.11",
    "dissect.evidence==3.13",
    "dissect.executable==1.11",
    "dissect.extfs==3.15",
    "dissect.fat==3.13",
    "dissect.ffs==3.12",
    "dissect.fve==4.6",
    "dissect.hypervisor==3.21",
    "dissect.jffs==1.6",
    "dissect.ntfs==3.16",
    "dissect.ole==3.12",
    "dissect.qnxfs==1.2",
    "dissect.regf==3.14",
    "dissect.shellitem==3.13",
    "dissect.squashfs==1.12",
    "dissect.target[full]==3.25.1",
    "dissect.thumbcache==1.11",
    "dissect.util==3.24",
    "dissect.vmfs==3.13",
    "dissect.volume==3.18",
    "dissect.xfs==3.13",
]
dynamic = ["version"]

[project.urls]
homepage = "https://dissect.tools"
documentation = "https://docs.dissect.tools"
repository = "https://github.com/fox-it/dissect"

[dependency-groups]
lint = [
    "typing_extensions",
    "ruff==0.13.1",
    "vermin",
]

[project.scripts]
dissect = "dissect.cli:main"

[tool.ruff]
line-length = 120
required-version = ">=0.13.1"
extend-exclude = ["tests/_data/**"]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = [
  "F",
  "E",
  "W",
  "I",
  "UP",
  "YTT",
  "ANN",
  "B",
  "C4",
  "DTZ",
  "T10",
  "FA",
  "ISC",
  "G",
  "INP",
  "PIE",
  "PYI",
  "PT",
  "Q",
  "RSE",
  "RET",
  "SLOT",
  "SIM",
  "TID",
  "TC",
  "PTH",
  "PLC",
  "TRY",
  "FLY",
  "PERF",
  "FURB",
  "RUF",
  "D"
]
ignore = [
    "E203", "B904", "UP024", "ANN002", "ANN003", "ANN204", "ANN401", "SIM105", "TRY003", "PLC0415",
    # Ignore some pydocstyle rules for now as they require a larger cleanup
    "D1",
    "D205",
    "D301",
    "D417",
    # Seems bugged: https://github.com/astral-sh/ruff/issues/16824
    "D402",
]
future-annotations = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-type-checking]
strict = true

[tool.ruff.lint.per-file-ignores]
"dissect/**" = ["INP001"]

[tool.ruff.lint.isort]
known-first-party = ["dissect.target"]
known-third-party = ["dissect"]
required-imports = ["from __future__ import annotations"]

[tool.setuptools.packages.find]
include = ["dissect", "dissect.*"]
namespaces = true

[tool.setuptools_scm]
