from __future__ import annotations

import os
import sys
import types
from typing import TYPE_CHECKING

import pytest
from dissect.cli import (
    _build_parser,
    _dispatch_module,
    _find_command,
    _iter_commands,
    _read_console_script,
    _resolve_sibling,
    main,
)

if TYPE_CHECKING:
    from pathlib import Path

    from pytest_benchmark.fixture import BenchmarkFixture

# A minimal console script wrapper, matching the format generated by pip/uv/setuptools.
WRAPPER = """\
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
from dissect.target.tools.shell import main
if __name__ == "__main__":
    sys.exit(main())
"""


@pytest.fixture
def fake_scripts(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Create a fake scripts directory next to a fake interpreter, mimicking an install layout.

    Pointing ``sys.executable`` at it makes ``_resolve_sibling`` hermetic: it no longer depends on how or where the
    tests themselves were installed.
    """
    bindir = tmp_path / "bin"
    bindir.mkdir()
    (bindir / "python").write_text("")
    (bindir / "target-shell").write_text(WRAPPER)
    monkeypatch.setattr(sys, "executable", str(bindir / "python"))
    return bindir


@pytest.fixture
def empty_scripts(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Like ``fake_scripts`` but without any command wrappers, so ``_resolve_sibling`` always misses."""
    bindir = tmp_path / "bin"
    bindir.mkdir()
    (bindir / "python").write_text("")
    monkeypatch.setattr(sys, "executable", str(bindir / "python"))
    return bindir


@pytest.fixture
def fake_module(monkeypatch: pytest.MonkeyPatch) -> str:
    """Register a lightweight fake tool module so dispatch can be exercised without importing a real tool."""
    name = "_dissect_cli_benchmark_fake"
    module = types.ModuleType(name)
    module.main = lambda: 0
    monkeypatch.setitem(sys.modules, name, module)
    return name


@pytest.fixture
def stub_dispatch(monkeypatch: pytest.MonkeyPatch) -> None:
    """Replace the actual tool invocation with a no-op so end-to-end benchmarks measure only dispatcher overhead."""
    monkeypatch.setattr("dissect.cli._dispatch_module", lambda *args, **kwargs: 0)


@pytest.fixture(autouse=True)
def _preserve_argv(monkeypatch: pytest.MonkeyPatch) -> None:
    # main() rewrites sys.argv; make sure each test starts (and leaves) it clean.
    monkeypatch.setattr(sys, "argv", list(sys.argv))


def run_main(argv: list[str]) -> int | None:
    """Invoke the unified entrypoint as if called from the command line, capturing the exit code."""
    sys.argv = ["dissect", *argv]
    try:
        return main()
    except SystemExit as exc:  # argparse (help/version/errors) exits rather than returning.
        return exc.code


# --- functional tests (always run) ---------------------------------------------------------------------------------


def test_resolve_sibling(fake_scripts: Path) -> None:
    # The flagship `target-` prefix takes precedence, so `shell` resolves to `target-shell`.
    assert _resolve_sibling("shell") == ("target-shell", "dissect.target.tools.shell", "main")


def test_resolve_sibling_miss(fake_scripts: Path) -> None:
    assert _resolve_sibling("does-not-exist") is None


def test_resolve_sibling_rejects_path_separator(fake_scripts: Path) -> None:
    assert _resolve_sibling(f"..{os.sep}evil") is None


def test_read_console_script(fake_scripts: Path) -> None:
    assert _read_console_script(str(fake_scripts / "target-shell")) == ("dissect.target.tools.shell", "main")


def test_read_console_script_missing(tmp_path: Path) -> None:
    assert _read_console_script(str(tmp_path / "nope")) is None


def test_dispatch_module(fake_module: str) -> None:
    argv_seen = []
    sys.modules[fake_module].main = lambda: argv_seen.extend(sys.argv) or 0

    assert _dispatch_module("fake-tool", fake_module, "main", ["a", "b"]) == 0
    # argv is rewritten so the tool sees itself invoked directly.
    assert argv_seen == ["fake-tool", "a", "b"]


def test_iter_commands_contains_target_shell() -> None:
    names = {name for name, _, _ in _iter_commands()}
    assert "shell" in names


def test_main_fast_path(fake_scripts: Path, stub_dispatch: None) -> None:
    assert run_main(["shell", "arg"]) == 0


def test_main_missing_sibling_falls_back(empty_scripts: Path, stub_dispatch: None) -> None:
    # No sibling wrapper, but `shell` still resolves via the metadata fallback.
    assert run_main(["shell"]) == 0


def test_main_unknown_command(empty_scripts: Path) -> None:
    assert run_main(["does-not-exist"]) == 2


def test_main_no_command(empty_scripts: Path) -> None:
    assert run_main([]) == 2


# --- benchmark tests (run only in the `benchmark` tox environment) -------------------------------------------------


@pytest.mark.benchmark
def test_benchmark_resolve_sibling(fake_scripts: Path, benchmark: BenchmarkFixture) -> None:
    """Fast path: resolving a command to its sibling console script."""
    result = benchmark(_resolve_sibling, "shell")
    assert result == ("target-shell", "dissect.target.tools.shell", "main")


@pytest.mark.benchmark
def test_benchmark_resolve_sibling_miss(fake_scripts: Path, benchmark: BenchmarkFixture) -> None:
    """Edge case: an unknown command returns None (which would trigger the metadata fallback)."""
    assert benchmark(_resolve_sibling, "does-not-exist") is None


@pytest.mark.benchmark
def test_benchmark_read_console_script(fake_scripts: Path, benchmark: BenchmarkFixture) -> None:
    """Fast path: parsing the `from <module> import <function>` line out of a wrapper."""
    path = str(fake_scripts / "target-shell")
    assert benchmark(_read_console_script, path) == ("dissect.target.tools.shell", "main")


@pytest.mark.benchmark
def test_benchmark_dispatch_module(fake_module: str, benchmark: BenchmarkFixture) -> None:
    """Fast path: the argv rewrite + import + call that dispatch performs."""
    assert benchmark(_dispatch_module, "fake-tool", fake_module, "main", []) == 0


@pytest.mark.benchmark
def test_benchmark_iter_commands(benchmark: BenchmarkFixture) -> None:
    """Fallback/help path: full metadata-based discovery of all dissect commands."""
    result = benchmark(lambda: list(_iter_commands()))
    assert any(name == "shell" for name, _, _ in result)


@pytest.mark.benchmark
def test_benchmark_find_command(benchmark: BenchmarkFixture) -> None:
    """Fallback path: a single metadata-based command lookup."""
    assert benchmark(_find_command, "shell") is not None


@pytest.mark.benchmark
def test_benchmark_build_help(benchmark: BenchmarkFixture) -> None:
    """Help path: building the parser, which reads every tool's docstring for the grouped listing."""
    parser = benchmark(_build_parser, with_commands=True)
    assert parser.epilog


# --- whole-entrypoint benchmarks: main() through its distinct paths ------------------------------------------------


@pytest.mark.benchmark
def test_benchmark_main_fast_path(fake_scripts: Path, stub_dispatch: None, benchmark: BenchmarkFixture) -> None:
    """End-to-end fast path: argv handling + sibling resolution + dispatch (tool stubbed)."""
    assert benchmark(run_main, ["shell", "arg"]) == 0


@pytest.mark.benchmark
def test_benchmark_main_missing_sibling(empty_scripts: Path, stub_dispatch: None, benchmark: BenchmarkFixture) -> None:
    """End-to-end fallback: sibling miss followed by a metadata-based lookup (tool stubbed)."""
    assert benchmark(run_main, ["shell"]) == 0


@pytest.mark.benchmark
def test_benchmark_main_unknown_command(empty_scripts: Path, benchmark: BenchmarkFixture) -> None:
    """End-to-end error path: sibling miss + metadata miss + argparse error rendering."""
    assert benchmark(run_main, ["does-not-exist"]) == 2


@pytest.mark.benchmark
def test_benchmark_main_help(benchmark: BenchmarkFixture) -> None:
    """End-to-end help path: builds and renders the flagship (target) listing."""
    assert benchmark(run_main, ["--help"]) == 0


@pytest.mark.benchmark
def test_benchmark_main_help_all(benchmark: BenchmarkFixture) -> None:
    """End-to-end help path: the full grouped listing, reading a docstring for every dissect tool installed."""
    assert benchmark(run_main, ["--help-all"]) == 0
